### ISSUE TITLE
on sms received doesn't work...

### ISSUE THREAD

**Issue by FlashThunder** [emilsedgh/modem#30]
Huawei E3131.

var modem = require('modem').Modem();

modem.open('/dev/ttyUSB0', function(){
	console.log('open');
	modem.on('sms received', function(){
		console.log('rcvd');
	});
});

When sending sms to the modem number, nothing happens. Modem is opened successfully, as I can send sms. Any idea why and how to debug that?

**Comment by emilsedgh** [comment]
Some modems open several ports (ttyUSB0-2). Try other ports please.

**Comment by FlashThunder** [comment]
Nice... on USB0, it was able to send sms, but on USB2 receive... basically it works... but have 2 more questions then...

1. Is it possible to delete sms that was just received from that event?
2. Why all messages contain more or less "\u0000" ? Examples:

text: 'Hii\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000'

 text: 'Yo\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000'

**Comment by emilsedgh** [comment]
Of course you can use ```modem.deleteMessage``` to delete an sms.

The `\u0000` are there because it seems that sms centers that deliver you the message, fill up all the blank space with `\u0000`. 

Feel free to ignore them to remove with something like this: text.replace(/\u0000/g, '')

**Comment by FlashThunder** [comment]
Thank you for your help and for really great job with that module. Was trying few other, and this one is simply the best! Thanx!

**Comment by emilsedgh** [comment]
If you are worried about your modem getting full, you can use something like this:
``` javascript
modem.on('memory full', function(memory) {
        modem.execute('AT+CPMS?', function(storage_info) {
            var storage_info = modem.parseResponse(storage_info);
            for(var i in storage_info) {
                if(storage_info[i] === memory) {
                    var used_index = parseInt(i)+1;
                    var total_index = parseInt(i)+2;
                    break;
                }
            }

            var used = storage_info[used_index];
            var total = storage_info[total_index];
            var toBeRemoved = parseInt(total/3);

            for(var i = 0; i<toBeRemoved; i++)
                modem.deleteMessage(i);
        });
    });
```

This code is almost copy/pasted, but what it does is this:

When modem's memory is filled, it finds out how much storage it has, how many items are used and removed 1/3 of modem's messages.

**Comment by FlashThunder** [comment]
Thank you, I will try that... I hope I can send at commands via same USB port...

**Comment by emilsedgh** [comment]
Of course you can. In the same code above we do it as well.
`modem.execute()` will let you run any AT command.
